# Generated by Django 2.0.6 on 2018-07-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='posted_at',
        ),
        migrations.AddField(
            model_name='event',
            name='Contact',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='event',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
